### ISSUE TITLE
Show the project line count instead of "LineCount" in status bar

### ISSUE THREAD

**Issue by Yzrsah** [lyzerk/vscode-linecounter#3]
Hi. I would be great if you could see the project's line count instead of the word "LineCount" in the status bar. It could use a nice octicon or other glyph next to the count. Or it could say "Lines: 5,042"

Since it would need to keep grepping to perform a live count, this could be a option.

**Comment by lyzerk** [comment]
I have added the feature. You can test after version >= 0.2.5.
